### PR TITLE
adding facebook api for fetching events from armenian tech groups

### PR DESCRIPTION
**Pull request by edgarkhanzadian**
Now silicondzor fetches info about events from armenian fb tech groups, but the info which silicondzor gets goes to console (haven't yet connected it to server and db) To get the data from fb you have to push LOGIN button, write username: 'update' and password: '1', then push 'sign in' button

### CODE REVIEW

**Comment by fxfactorial** [comment]
Great job. 

0) I just added a commit to make it easier to develop without HTTPs on, you'll need to rebase of the latest commit. 
1) I don't think you need to dynamically make the script tag, you can just add it like here: https://github.com/fxfactorial/silicondzor/blob/master/backend/server.js#L84 
2) Piggy backing off of 1, since you are doing the initial render on the server side, you can make the app ID, which I guess is like your ID with FB be an environment variable, no need to hard code it like this: https://github.com/fxfactorial/silicondzor/pull/20/files#diff-ff25e790247d85a67e6c336abcc5edafR8
3) Also need to make a new SQL table, etc and other things mentioned. 
4) It shouldn't be from the end user (front end), but the backend needs to do the querying. This should have nothing to do with the front end. 

The general outline: 
1) Node backend periodically queries the FB API for events, maybe once every 48 hours
2) After getting the data, it cleans for our data base format, like the date time, etc. 
3) Once data cleaned up, you insert into our sqlite database that new data, the general idea is something like an upsert. 
4) You should make a new table for recording these events by group
5) Now end user will see all the events.

**Comment by rht** [comment]
I have a pending untested WIP in a local branch (making sure the implementation is succinct).

```js
const FB = require('fb');
var groups = {iterate: 410797219090898, ArmTechCongress: 214940895208239, socialbridgeapp: 629600800545917, MICArmenia:195461300492991};
groups.forEach((group_name, group_id) => {
  FB.api(`${group_id}/events?`, {access_token: 'token'})
    .then(res => {
      var data = JSON.parse(res).data;
      var metadata = data.map(each => {
        db_promises.run(`insert or replace into event values ($title, $all_day, $start, $end, $description, $creator)`, {
          $title: each.name,
          $all_day: each.start_time === each.end_time,
          $start: each.start_time,
          $end: each.end_time,
          $description: each.description,
          $creator: `@${group_name}`
        });
      });
    });
});
```

Sorry I should have pushed this so it could be reused. Everything is done in the backend.
FB doesn't have an official nodejs lib, but I believe https://www.npmjs.com/package/fb has been used a lot in the community.

**Comment by rht** [comment]
The DB insertion code for the event https://github.com/fxfactorial/silicondzor/blob/96920f479311a705f5ca2311f98094c9ca11b24c/backend/server.js#L201-L209 and for here could be deduplicated.

**Comment by fxfactorial** [comment]
Awesome.

For that sample, I think it would be better to use Promise.all

**Comment by rht** [comment]
Ah right, tho DB mutate operation is sync-locked still. Say if this could be nailed before the first event, @edgarkhanzadyan ?

**Comment by fxfactorial** [comment]
@edgarkhanzadyan Implemented in https://github.com/fxfactorial/silicondzor/pull/21 

Try another github issue!

**Pull request closed without merging**
